[package]
name = "ferrite-lithic"
description = "The front-end DSL for Ferrite Lithic: build a circuit by writing arithmetic"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
ferrite-lithic-bits.workspace = true
ferrite-lithic-ir.workspace = true

[dev-dependencies]
ferrite-lithic-bits = { path = "../ferrite-lithic-bits", version = "0.0.1" }
ferrite-lithic-derive = { path = "../ferrite-lithic-derive", version = "0.0.1" }
ferrite-lithic-rtl = { path = "../ferrite-lithic-rtl", version = "0.0.1" }
ferrite-lithic-sim = { path = "../ferrite-lithic-sim", version = "0.0.1" }
proptest = "1.11"
