//! Whole modules as text, and the properties the text is supposed to have.
//!
//! # Why goldens and not a simulator
//!
//! The design notes keep snapshot tests on emitted Verilog
//! ([`docs/design-notes.md`](https://github.com/ostrium-labs/ferrite-lithic/blob/dev/docs/design-notes.md)
//! §6) and *substitute* for Hardcaml's golden waveforms, because those are ASCII
//! renders from a proprietary external library. So: compare text.
//!
//! Each golden below is a design small enough to read in full and to check against
//! the IR by hand. When one of them changes, the change is either a decision worth
//! arguing about or a bug, and both are visible in the diff. `tests/iverilog.rs`
//! runs the same text through a real parser when one is installed.
//!
//! # The four properties
//!
//! Beyond the text, four things are asserted on their own because they are the
//! claims the crate makes rather than the output it happens to produce: byte
//! stability, structural stability across arenas, section order, and the
//! refusals.

#![allow(clippy::unwrap_used, clippy::expect_used)]

use ferrite_lithic::Design;
use ferrite_lithic_bits::Bits;
use ferrite_lithic_ir::{Circuit, NodeId};
use ferrite_lithic_rtl::{Error, Module, emit_library};

/// The accumulator from the front end's own docs: eight bits of state that add `d`
/// on every edge.
fn accumulator() -> (Design, ferrite_lithic::Signal) {
    let d = Design::new();
    let clk = d.input("clk", 1).unwrap();
    let data = d.input("d", 8).unwrap();
    let acc = d.wire(8).unwrap();
    let next = d.add(&acc, &data).unwrap();
    let next = d
        .reg(&next, &clk, &d.constant(false), &d.constant(false))
        .unwrap();
    d.drive(&acc, &next).unwrap();
    d.output("acc", 8, &acc).unwrap();
    (d, clk)
}

/// A module with a clock, built from a design's declared ports.
fn module(d: &Design, clock: &ferrite_lithic::Signal, name: &str) -> Module {
    Module::new(
        name,
        d.build().unwrap(),
        clock.id(),
        d.input_ports().iter().map(|s| s.id()).collect(),
        d.output_ports().iter().map(|s| s.id()).collect(),
    )
}

/// The smallest module with state in it.
#[test]
fn an_accumulator_emits_the_expected_module() {
    let (d, clk) = accumulator();
    let text = module(&d, &clk, "accumulator").emit().unwrap();
    let expected = r#"// Generated by ferrite-lithic-rtl. Do not edit; regenerate from the design.
// module `accumulator`
module accumulator (
  input  wire [0:0] clk,
  input  wire [7:0] d,
  output wire [7:0] acc
);
  wire [7:0] signal_Wire;
  wire [7:0] signal_Add;
  reg [7:0] signal_Reg;

  assign signal_Add = signal_Wire + d;
  always @(posedge clk) begin
    signal_Reg <= signal_Add;
  end

  assign signal_Wire = signal_Reg;

  assign acc = signal_Wire;

endmodule
"#;
    assert_eq!(text, expected);
}

/// A register with both control inputs tied low emits the shortest honest form: no
/// reset test that cannot fire, and no clear test that cannot fire.
#[test]
fn a_register_with_tied_low_controls_has_no_control_tests() {
    let (d, clk) = accumulator();
    let text = module(&d, &clk, "accumulator").emit().unwrap();
    assert!(text.contains("always @(posedge clk) begin"), "{text}");
    assert!(text.contains("signal_Reg <= signal_Add;"), "{text}");
    assert!(!text.contains("if ("), "{text}");
}

/// `clear` holds; `reset` clears to zero. Both are asserted separately because both
/// are divergences from the reference's text, and neither is visible in a glance at
/// a golden.
#[test]
fn a_cleared_register_holds_and_a_reset_one_clears() {
    let d = Design::new();
    let clk = d.input("clk", 1).unwrap();
    let reset = d.input("reset", 1).unwrap();
    let hold = d.input("hold", 1).unwrap();
    let data = d.input("data", 8).unwrap();
    let reg = d.reg(&data, &clk, &reset, &hold).unwrap();
    d.output("q", 8, &reg).unwrap();
    let text = module(&d, &clk, "held").emit().unwrap();
    assert!(
        text.contains("if (reset == 1'b1) signal_Reg <= 8'h00;"),
        "{text}"
    );
    // `q <= q`, not `q <= 8'h00`: our `clear` gates the update, and a zero here
    // would disagree with the simulator.
    assert!(
        text.contains("else if (hold) signal_Reg <= signal_Reg;"),
        "{text}"
    );
    assert!(text.contains("else signal_Reg <= data;"), "{text}");
}

/// Memories, read ports, and a `case` node — the three shapes that need a block of
/// their own rather than an `assign`.
#[test]
fn memories_and_cases_emit_the_expected_module() {
    let d = Design::new();
    let clk = d.input("clk", 1).unwrap();
    let rst = d.input("rst", 1).unwrap();
    let we = d.input("we", 1).unwrap();
    let addr = d.input("addr", 4).unwrap();
    let data = d.input("data", 8).unwrap();
    let mem = d.mem(8, 16).unwrap();
    d.write_port(&mem, &data, &addr, &we).unwrap();
    let read = d.read_port(&mem, &addr, &we).unwrap();
    let held = d.reg(&read, &clk, &rst, &d.constant(false)).unwrap();
    let kind = d.slice(&data, 0, 2).unwrap();
    let wide = d.zero_extend(&kind, 8).unwrap();
    let picked = d
        .case_(&kind, &[(0, held.clone()), (1, wide.clone())], &data)
        .unwrap();
    d.output("q", 8, &picked).unwrap();
    let text = module(&d, &clk, "memory_and_case").emit().unwrap();
    let expected = r#"// Generated by ferrite-lithic-rtl. Do not edit; regenerate from the design.
// module `memory_and_case`
module memory_and_case (
  input  wire [0:0] clk,
  input  wire [0:0] rst,
  input  wire [0:0] we,
  input  wire [3:0] addr,
  input  wire [7:0] data,
  output wire [7:0] q
);
  reg [7:0] signal_Mem [0:15];
  wire [7:0] signal_ReadPort;
  reg [7:0] signal_Reg;
  wire [1:0] signal_Select;
  wire [1:0] signal_Select_1;
  wire [7:0] signal_Cat;
  reg [7:0] signal_Case;

  always @(posedge clk) begin
    if (we) signal_Mem[addr] <= data;
  end
  assign signal_ReadPort = we ? signal_Mem[addr] : '0;
  always @(posedge clk) begin
    if (rst == 1'b1) signal_Reg <= 8'h00;
    else signal_Reg <= signal_ReadPort;
  end
  assign signal_Select = data[0 +: 2];
  assign signal_Select_1 = signal_Select[0 +: 2];
  assign signal_Cat = {6'h00, signal_Select_1};
  always @* begin
    case (signal_Select)
      2'h0: signal_Case = signal_Reg;
      2'h1: signal_Case = signal_Cat;
      default: signal_Case = data;
    endcase
  end

  assign q = signal_Case;

endmodule
"#;
    assert_eq!(text, expected);
}

/// Every combinational node kind, in one module, so no kind can be added or changed
/// without this golden moving.
#[test]
fn every_operation_has_a_spelling() {
    let d = Design::new();
    let clk = d.input("clk", 1).unwrap();
    let rst = d.input("input", 1).unwrap();
    let a = d.input("a", 8).unwrap();
    let b = d.input("b", 8).unwrap();
    let addr = d.input("addr", 4).unwrap();
    let we = d.input("we", 1).unwrap();

    let sum = d.add(&a, &b).unwrap();
    let product = d.mul(&a, &b).unwrap();
    let quotient = d.udiv(&a, &b).unwrap();
    let squotient = d.sdiv(&a, &b).unwrap();
    let srem = d.srem(&a, &b).unwrap();
    let urem = d.urem(&a, &b).unwrap();
    let cmp = d.slt(&a, &b).unwrap();
    let ucmp = d.uge(&a, &b).unwrap();
    let eq = d.eq(&a, &b).unwrap();
    let inv = d.not(&a);
    let low = d.slice(&sum, 0, 4).unwrap();
    let pair_wide = d.concat(&[low, product.clone()]).unwrap();
    let pair = d.truncate(&pair_wide, 8).unwrap();
    let rep = d.replicate(&d.ones(1).unwrap(), 4).unwrap();
    let rep8 = d.zero_extend(&rep, 8).unwrap();
    let both = d.and(&cmp, &ucmp).unwrap();
    let both8 = d.zero_extend(&both, 8).unwrap();
    let sel = d.ite(&eq, &quotient, &squotient).unwrap();
    let mixed = d.or(&sel, &both8).unwrap();
    let wide = d.xor(&mixed, &pair).unwrap();
    let combined = d.or(&wide, &rep8).unwrap();
    let chosen = d
        .case_(&cmp, &[(0, srem.clone()), (1, urem.clone())], &inv)
        .unwrap();
    let total = d.add(&combined, &chosen).unwrap();
    let diff = d.sub(&total, &a).unwrap();

    let mem = d.mem(8, 16).unwrap();
    d.write_port(&mem, &a, &addr, &we).unwrap();
    let read = d.read_port(&mem, &addr, &d.constant(true)).unwrap();
    let held = d.reg(&diff, &clk, &rst, &d.constant(false)).unwrap();
    let from_mem = d.add(&held, &read).unwrap();
    d.output("q", 8, &from_mem).unwrap();
    let depth = Bits::constant(16, 32).unwrap();
    let sub = d
        .instance("fifo", &[("DEPTH", depth)], &[a.clone(), b.clone()], 8)
        .unwrap();
    d.output("last", 8, &sub).unwrap();

    let text = module(&d, &clk, "every_op").emit().unwrap();
    for expected in [
        "assign signal_Add = a + b;",
        "assign signal_Mul = a * b;",
        "assign signal_UDiv = a / b;",
        "assign signal_SDiv = $signed(a) / $signed(b);",
        "assign signal_SRem = $signed(a) % $signed(b);",
        "assign signal_URem = a % b;",
        "assign signal_Slt = $signed(a) < $signed(b);",
        "assign signal_Uge = a >= b;",
        "assign signal_Eq = a == b;",
        "assign signal_Not = ~a;",
        "assign signal_Select = signal_Add[0 +: 4];",
        "assign signal_Replicate = {4{1'h1}};",
        "assign signal_BitAnd = signal_Slt & signal_Uge;",
        "assign signal_Ite = signal_Eq ? signal_UDiv : signal_SDiv;",
        "assign signal_BitOr = signal_Ite | signal_Cat_2;",
        "assign signal_BitXor = signal_BitOr ^ signal_Select_1;",
        "assign signal_BitOr_1 = signal_BitXor | signal_Cat_1;",
        "assign signal_Sub = signal_Add_1 - a;",
        "reg [7:0] signal_Case;",
        "always @(posedge clk) begin",
        "if (we) signal_Mem[addr] <= a;",
        "assign signal_ReadPort = 1'h1 ? signal_Mem[addr] : '0;",
        "fifo #(.DEPTH(32'h00000010)) u_Instance (",
        ".i0 (a),",
        ".i1 (b),",
        ".o0 (signal_Instance)",
    ] {
        assert!(text.contains(expected), "missing {expected:?} in\n{text}");
    }
    // The reserved word in the port list, escaped.
    assert!(text.contains("input  wire [0:0] input_,"), "{text}");
}

/// A multiply is full precision because of the width of the wire it assigns to,
/// which is the only reason no cast is needed. Asserted separately because it is a
/// claim about Verilog's sizing rules, not about the text.
#[test]
fn a_multiply_is_declared_at_the_sum_of_its_operands() {
    let d = Design::new();
    let a = d.input("a", 8).unwrap();
    let b = d.input("b", 8).unwrap();
    let product = d.mul(&a, &b).unwrap();
    d.output("out", 16, &product).unwrap();
    let text = Module::combinational(
        "mul",
        d.build().unwrap(),
        d.input_ports().iter().map(|s| s.id()).collect(),
        d.output_ports().iter().map(|s| s.id()).collect(),
    )
    .emit()
    .unwrap();
    assert!(text.contains("wire [15:0] signal_Mul;"), "{text}");
    assert!(text.contains("assign signal_Mul = a * b;"), "{text}");
}

/// Emitting the same program twice produces the same bytes.
#[test]
fn emitting_twice_produces_the_same_bytes() {
    let (d, clk) = accumulator();
    let first = module(&d, &clk, "accumulator").emit().unwrap();
    let second = module(&d, &clk, "accumulator").emit().unwrap();
    assert_eq!(first, second);
}

/// Two separately built circuits produce the same bytes. This is the property the
/// arena buys: node ids are construction order, so there is no uid counter to reset
/// and no normalisation pass to go wrong.
#[test]
fn two_arenas_built_the_same_way_agree() {
    let (first, first_clk) = accumulator();
    let (second, second_clk) = accumulator();
    let a = module(&first, &first_clk, "accumulator").emit().unwrap();
    let b = module(&second, &second_clk, "accumulator").emit().unwrap();
    assert_eq!(a, b);
}

/// The preamble carries nothing that changes between runs.
#[test]
fn the_preamble_has_nothing_that_moves() {
    let (d, clk) = accumulator();
    let text = module(&d, &clk, "accumulator").emit().unwrap();
    let header: Vec<&str> = text.lines().take(2).collect();
    assert_eq!(
        header,
        vec![
            "// Generated by ferrite-lithic-rtl. Do not edit; regenerate from the design.",
            "// module `accumulator`",
        ]
    );
    for banned in ["20", "Z", "rustc", "src/"] {
        assert!(
            !header[0].contains(banned),
            "the preamble mentions {banned:?}: {}",
            header[0]
        );
    }
}

/// Sections appear in the reference's order, so a diff of one does not churn
/// another.
#[test]
fn sections_appear_in_the_fixed_order() {
    let d = Design::new();
    let clk = d.input("clk", 1).unwrap();
    let data = d.input("data", 8).unwrap();
    let sum = d.add(&data, &data).unwrap();
    let held = d
        .reg(&sum, &clk, &d.constant(false), &d.constant(false))
        .unwrap();
    let wired = d.wire(8).unwrap();
    d.drive(&wired, &held).unwrap();
    d.output("q", 8, &wired).unwrap();
    let text = module(&d, &clk, "order").emit().unwrap();
    let ports = text.find("module order (").unwrap();
    let declaration = text.find("wire [7:0] signal_Add;").unwrap_or(usize::MAX);
    let statement = text.find("assign signal_Add").unwrap_or(usize::MAX);
    let alias = text.find("assign signal_Wire").unwrap_or(usize::MAX);
    let output = text.find("assign q").unwrap_or(usize::MAX);
    let end = text.find("endmodule").unwrap();
    assert!(ports < declaration, "{text}");
    assert!(declaration < statement, "{text}");
    assert!(statement < alias, "{text}");
    assert!(alias < output, "{text}");
    assert!(output < end, "{text}");
}

/// Logic that reaches no output is not emitted, which is what a vendor toolchain
/// would do with it anyway.
#[test]
fn logic_that_feeds_no_output_is_not_emitted() {
    let d = Design::new();
    let a = d.input("a", 8).unwrap();
    let b = d.input("b", 8).unwrap();
    let dead = d.add(&a, &b).unwrap();
    d.set_name(&dead, "dead").unwrap();
    let live = d.not(&a);
    d.output("out", 8, &live).unwrap();
    let text = Module::combinational(
        "pruned",
        d.build().unwrap(),
        d.input_ports().iter().map(|s| s.id()).collect(),
        d.output_ports().iter().map(|s| s.id()).collect(),
    )
    .emit()
    .unwrap();
    assert!(text.contains("assign signal_Not = ~a;"), "{text}");
    assert!(!text.contains("dead"), "{text}");
}

/// A literal has no edge, so there is no text that means "clocked by one".
#[test]
fn a_literal_clock_is_refused() {
    let mut circuit = Circuit::new();
    let data = circuit.wire(8).unwrap();
    circuit.set_name(data, "data").unwrap();
    let low = circuit.constant(Bits::constant(0, 1).unwrap());
    let reg = circuit
        .reg(data, low, low, low)
        .expect("the graph itself is legal: a literal clock is a description problem");
    let out = circuit.wire(8).unwrap();
    circuit.set_name(out, "out").unwrap();
    circuit.drive(out, reg).unwrap();
    let err = Module::new("lit", circuit, low, vec![data], vec![out])
        .emit()
        .unwrap_err();
    assert!(matches!(err, Error::ConstantClock { .. }), "{err:?}");
}

/// A second clock domain is refused rather than folded into the first, which is the
/// same boundary the simulator reports as `MultipleClocks`.
#[test]
fn a_second_clock_domain_is_refused() {
    let mut circuit = Circuit::new();
    let data = circuit.wire(8).unwrap();
    let first = circuit.wire(1).unwrap();
    let second = circuit.wire(1).unwrap();
    for (id, name) in [(data, "data"), (first, "clk"), (second, "clk2")] {
        circuit.set_name(id, name).unwrap();
    }
    let low = circuit.constant(Bits::constant(0, 1).unwrap());
    let reg = circuit.reg(data, second, low, low).unwrap();
    let out = circuit.wire(8).unwrap();
    circuit.set_name(out, "out").unwrap();
    circuit.drive(out, reg).unwrap();
    let err = Module::new("two", circuit, first, vec![data, first, second], vec![out])
        .emit()
        .unwrap_err();
    match err {
        Error::ClockMismatch {
            found, expected, ..
        } => {
            assert_eq!(found, second);
            assert_eq!(expected, first);
        }
        other => panic!("{other:?}"),
    }
}

/// A module built without a clock has nowhere to put an edge.
#[test]
fn state_in_a_clockless_module_is_refused() {
    let mut circuit = Circuit::new();
    let data = circuit.wire(8).unwrap();
    let clk = circuit.wire(1).unwrap();
    for (id, name) in [(data, "data"), (clk, "clk")] {
        circuit.set_name(id, name).unwrap();
    }
    let low = circuit.constant(Bits::constant(0, 1).unwrap());
    let reg = circuit.reg(data, clk, low, low).unwrap();
    let out = circuit.wire(8).unwrap();
    circuit.set_name(out, "out").unwrap();
    circuit.drive(out, reg).unwrap();
    let err = Module::combinational("clockless", circuit, vec![data, clk], vec![out])
        .emit()
        .unwrap_err();
    assert!(
        matches!(
            err,
            Error::NoClock {
                kind: "register",
                ..
            }
        ),
        "{err:?}"
    );
}

/// A memory is an array, so there is no expression for it.
#[test]
fn a_memory_used_as_a_value_is_refused() {
    let mut circuit = Circuit::new();
    let addr = circuit.wire(4).unwrap();
    let enable = circuit.wire(1).unwrap();
    let data = circuit.wire(8).unwrap();
    for (id, name) in [(addr, "addr"), (enable, "en"), (data, "data")] {
        circuit.set_name(id, name).unwrap();
    }
    // No write ports, so nothing needs a clock and the value error is what surfaces
    // rather than the clock one.
    let mem = circuit.mem(8, 4).unwrap();
    circuit.set_name(mem, "mem").unwrap();
    // A wire driven by the whole array: the mistake this refusal exists for.
    let whole = circuit.wire(8).unwrap();
    circuit.set_name(whole, "whole").unwrap();
    circuit.drive(whole, mem).unwrap();
    let out = circuit.wire(8).unwrap();
    circuit.set_name(out, "out").unwrap();
    circuit.drive(out, whole).unwrap();
    let err = Module::combinational("array", circuit, vec![addr, enable, data], vec![out])
        .emit()
        .unwrap_err();
    assert!(
        matches!(err, Error::NotAValue { kind: "Mem", .. }),
        "{err:?}"
    );
}

/// A hand-built node with no width has no Verilog expression. The constructors
/// refuse both of these; `add_node` does not check, which is what makes them worth
/// catching here. A `cat` is how such a node gets into a graph at all, since it is
/// the one node kind with no equal-width requirement on its operands.
#[test]
fn a_node_with_no_width_has_no_expression() {
    use ferrite_lithic_ir::Node;

    for node in [
        Node::Select {
            value: NodeId::from_index(0),
            offset: 0,
            len: 0,
        },
        Node::Replicate {
            value: NodeId::from_index(0),
            count: 0,
        },
    ] {
        let kind = node.kind();
        let mut circuit = Circuit::new();
        let a = circuit.wire(8).unwrap();
        circuit.set_name(a, "a").unwrap();
        let empty = circuit.add_node(node).unwrap();
        let joined = circuit.cat(a, empty).unwrap();
        let out = circuit.wire(8).unwrap();
        circuit.set_name(out, "out").unwrap();
        circuit.drive(out, joined).unwrap();
        let err = Module::combinational("nowidth", circuit, vec![a], vec![out])
            .emit()
            .unwrap_err();
        assert!(
            matches!(err, Error::NotAValue { kind: got, .. } if got == kind),
            "{err:?}"
        );
    }
}

/// A module name is the one identifier that cannot be *mangled*.
///
/// There is no pool of names for it to take a free one from, and a submodule has to
/// stay findable under the name its instantiation site spells. It is still
/// legalised, though, and the parser found the gap: `iverilog` rejects `module
/// signed (` with a syntax error, and a golden reading `module signed (` is
/// indistinguishable from a golden reading `module signed (`.
#[test]
fn a_module_name_is_legalised() {
    let mut circuit = Circuit::new();
    let a = circuit.wire(8).unwrap();
    circuit.set_name(a, "a").unwrap();
    let out = circuit.wire(8).unwrap();
    circuit.set_name(out, "out").unwrap();
    circuit.drive(out, a).unwrap();

    let module = Module::combinational("signed", circuit, vec![a], vec![out]);
    assert_eq!(module.name(), "signed_");
    let text = module.emit().unwrap();
    assert!(text.contains("\nmodule signed_ ("), "{text}");
    assert!(text.contains("// module `signed_`"), "{text}");

    let mut circuit = Circuit::new();
    let a = circuit.wire(8).unwrap();
    circuit.set_name(a, "a").unwrap();
    let out = circuit.wire(8).unwrap();
    circuit.set_name(out, "out").unwrap();
    circuit.drive(out, a).unwrap();
    let module = Module::combinational("9lives-core", circuit, vec![a], vec![out]);
    assert_eq!(module.name(), "_9lives_core");
    assert!(
        module.emit().unwrap().contains("\nmodule _9lives_core ("),
        "a leading digit and an illegal character both have to go"
    );
}

/// The instantiation site legalises the submodule name the same way the definition
/// did, or `module signed_` would be instantiated as `signed` and the error would
/// be about a missing module.
#[test]
fn an_instantiation_legalises_the_module_name() {
    let mut circuit = Circuit::new();
    let a = circuit.wire(8).unwrap();
    circuit.set_name(a, "a").unwrap();
    let sub = circuit
        .instance("case-analyzer", Vec::new(), vec![a], 8)
        .unwrap();
    let out = circuit.wire(8).unwrap();
    circuit.set_name(out, "out").unwrap();
    circuit.drive(out, sub).unwrap();
    let text = Module::combinational("top", circuit, vec![a], vec![out])
        .emit()
        .unwrap();
    assert!(text.contains("  case_analyzer u_Instance ("), "{text}");
}

/// An empty module name is the one thing that cannot be legalised into something.
#[test]
fn an_empty_module_name_is_refused() {
    let mut circuit = Circuit::new();
    let a = circuit.wire(8).unwrap();
    circuit.set_name(a, "a").unwrap();
    let out = circuit.wire(8).unwrap();
    circuit.set_name(out, "out").unwrap();
    circuit.drive(out, a).unwrap();
    let err = Module::combinational("", circuit, vec![a], vec![out])
        .emit()
        .unwrap_err();
    assert!(matches!(err, Error::EmptyModuleName), "{err:?}");
}

/// An output with no driver is refused, rather than emitted as a floating net that
/// a lint would catch much later.
#[test]
fn an_undriven_output_port_is_refused() {
    let mut circuit = Circuit::new();
    let a = circuit.wire(8).unwrap();
    let out = circuit.wire(8).unwrap();
    circuit.set_name(a, "a").unwrap();
    circuit.set_name(out, "out").unwrap();
    // `check_with_inputs` passes: an undriven wire is a port if it is listed as one,
    // and this output port is not listed as an input.
    let err = Module::combinational("floating", circuit, vec![a], vec![out])
        .emit()
        .unwrap_err();
    assert!(matches!(err, Error::UndrivenPort { .. }), "{err:?}");
}

/// Two instances of one submodule produce one module definition.
#[test]
fn a_library_collapses_same_named_modules() {
    let (d, clk) = accumulator();
    let first = module(&d, &clk, "accumulator");
    let (other, other_clk) = accumulator();
    let second = module(&other, &other_clk, "accumulator");
    let text = emit_library(&[&first, &second]).unwrap();
    assert_eq!(text.matches("module accumulator (").count(), 1, "{text}");
    assert_eq!(text.matches("endmodule").count(), 1, "{text}");
}

/// Two modules with one name and different ports cannot both be defined.
#[test]
fn a_library_refuses_two_modules_that_disagree_about_their_ports() {
    let (d, clk) = accumulator();
    let first = module(&d, &clk, "thing");
    let mut circuit = Circuit::new();
    let a = circuit.wire(1).unwrap();
    let out = circuit.wire(1).unwrap();
    circuit.set_name(a, "a").unwrap();
    circuit.set_name(out, "out").unwrap();
    circuit.drive(out, a).unwrap();
    let second = Module::combinational("thing", circuit, vec![a], vec![out]);
    let err = emit_library(&[&first, &second]).unwrap_err();
    assert!(
        matches!(err, Error::ModuleSignatureConflict { ref name, .. } if name == "thing"),
        "{err:?}"
    );
}

/// A module's signature is its port counts, widths and naming scheme.
#[test]
fn a_signature_is_the_port_shape() {
    let (d, clk) = accumulator();
    let m = module(&d, &clk, "accumulator");
    let signature = m.signature().unwrap();
    assert_eq!(signature.inputs, 2);
    assert_eq!(signature.outputs, 1);
    assert_eq!(signature.input_widths, vec![1, 8]);
    assert_eq!(signature.output_widths, vec![8]);
}
